name = "Create: Techified"
author = "pineapple, wrldmap"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20106d54f9b58951761ed73a97170429cb562edb9010e67ad36f5a9d0fd8da38"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
